package com.objectstyle.appfirst.jmx.collector.config;

public interface Constants {
    String COMMAND_KEYWORD = "jmx_command";
    String ATTRIBUTE_KEY_PREFIX = "-";
    String VIRTUAL_MACHINE_MATCH_PATTERN_KEY = ATTRIBUTE_KEY_PREFIX + "P";
    String MBEAN_NAME_KEY = ATTRIBUTE_KEY_PREFIX + "O";
    String MBEAN_ATTRIBUTE_KEY = ATTRIBUTE_KEY_PREFIX + "A";
    String MBEAN_ATTRIBUTE_KEY_KEY = ATTRIBUTE_KEY_PREFIX + "K";
    String VIRTUAL_MACHINE_URL_KEY = ATTRIBUTE_KEY_PREFIX + "U";
    String WARNING_THRESHOLD_KEY = ATTRIBUTE_KEY_PREFIX + "W";
    String CRITICAL_THRESHOLD_KEY = ATTRIBUTE_KEY_PREFIX + "C";
}
